# declare resources
resources:
- name: source-code
  type: git
  icon: github-circle
  source:
    uri: https://github.com/pkhamdee/dotnet-api
    branch: develop
    private_key: ((github-private-key))

- name: source-release
  type: git
  icon: github-circle
  source:
    uri: https://github.com/pkhamdee/dotnet-api
    branch: release
    private_key: ((github-private-key))

# list out jobs
jobs:
# first job runs unit tests
- name: run-unit-tests
  build_logs_to_retain: 5
  plan:
  - get: source-code
    trigger: true
  - task: run-tests
    config: 
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: mcr.microsoft.com/dotnet/core/sdk}
      inputs:
      - name: source-code
      run:
          path: sh
          args:
          - -exec
          - |
            dotnet restore
            dotnet build
            dotnet test ./source-code/seroter-api-k8s.csproj     

# second job produces a container
- name: promote-to-release
  build_logs_to_retain: 5
  plan:
  - in_parallel:
    - get: source-code 
      trigger: true
      passed:
      - run-unit-tests
    - get: source-release
  - put: source-release
    params:
      repository: source-code
